language: node_js

sudo: required
services:
  - docker

before_install:
  - docker build -t sis88/docker-react Dockerfile.dev .
  
  
script:
  - docker run sis88/docker-react npm run test -- --coverage