language: node_js
node_js:
  - 8

sudo: required
services:
  - docker

before_install:
  - docker build -t sis88/docker-react -f Dockerfile.dev .
  
  
script:
  - docker run -e CI=true sis88/docker-react npm run test -- --coverage